### ISSUE TITLE
Model class taggit.models.Tag doesn't declare an explicit app_labe

### ISSUE THREAD

**Issue by jhonvidal** [Pyc0kw4k/djangocms_miblog#1]
I have this error,
I'm working with django Django == 1.9.5,
django-cms == 3.2.3,

the error is as follows:

Unhandled exception in thread started by <function wrapper at 0x7f18d0ccc230>
Traceback (most recent call last):
  File "/home/jhon/MEGAsync/binanova/proyectos/binacorporation/milosbolivia/entornos/milosbolivia/local/lib/python2.7/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/home/jhon/MEGAsync/binanova/proyectos/binacorporation/milosbolivia/entornos/milosbolivia/local/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "/home/jhon/MEGAsync/binanova/proyectos/binacorporation/milosbolivia/entornos/milosbolivia/local/lib/python2.7/site-packages/django/utils/autoreload.py", line 249, in raise_last_exception
    six.reraise(*_exception)
  File "/home/jhon/MEGAsync/binanova/proyectos/binacorporation/milosbolivia/entornos/milosbolivia/local/lib/python2.7/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/home/jhon/MEGAsync/binanova/proyectos/binacorporation/milosbolivia/entornos/milosbolivia/local/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/jhon/MEGAsync/binanova/proyectos/binacorporation/milosbolivia/entornos/milosbolivia/local/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/home/jhon/MEGAsync/binanova/proyectos/binacorporation/milosbolivia/entornos/milosbolivia/local/lib/python2.7/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/jhon/MEGAsync/binanova/proyectos/binacorporation/milosbolivia/entornos/milosbolivia/local/lib/python2.7/site-packages/blog/models.py", line 7, in <module>
    from taggit.managers import TaggableManager
  File "/home/jhon/MEGAsync/binanova/proyectos/binacorporation/milosbolivia/entornos/milosbolivia/local/lib/python2.7/site-packages/taggit/managers.py", line 16, in <module>
    from taggit.models import CommonGenericTaggedItemBase, TaggedItem
  File "/home/jhon/MEGAsync/binanova/proyectos/binacorporation/milosbolivia/entornos/milosbolivia/local/lib/python2.7/site-packages/taggit/models.py", line 98, in <module>
    class Tag(TagBase):
  File "/home/jhon/MEGAsync/binanova/proyectos/binacorporation/milosbolivia/entornos/milosbolivia/local/lib/python2.7/site-packages/django/db/models/base.py", line 102, in __new__
    "INSTALLED_APPS." % (module, name)
RuntimeError: Model class taggit.models.Tag doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.

****************************

my settings is: 

`
INSTALLED_APPS = (
    ...
    'djangocms_admin_style',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.admin',
    'django.contrib.sites',
    'django.contrib.sitemaps',
    'django.contrib.staticfiles',
    'django.contrib.messages',
    'cms',
    'menus',
    'sekizai',
    'treebeard',
    'djangocms_text_ckeditor',
    'djangocms_style',
    'djangocms_column',
    'djangocms_file',
    'djangocms_googlemap',
    'djangocms_inherit',
    'djangocms_link',
    'djangocms_picture',
    'djangocms_teaser',
    'djangocms_video',
    'reversion',
    'milosbolivia',
    'portal',
    'cmsplugin_contact_plus',
    'sorl.thumbnail',
    'djangocms_slider',
    'blog',
)`

**Comment by jhonvidal** [comment]
help me !

**Comment by Pyc0kw4k** [comment]
Hello,

i think you didn't have registered 'taggit' on your INSTALLED_APPS

 #Requirements
    'easy_thumbnails',
    'filer',
    'mptt',
    'taggit',

you can see INSTALLED_APPS on the example apps in the project.

**Comment by jhonvidal** [comment]
solved !
